name: Main

on:
  push:

env:
  KOSLI_DRY_RUN: ${{ vars.KOSLI_DRY_RUN }}           # false
  KOSLI_HOST: ${{ vars.KOSLI_HOST }}                 # https://app.kosli.com
  KOSLI_ORG: ${{ vars.KOSLI_ORG }}                   # cyber-dojo
  KOSLI_FLOW: ${{ vars.KOSLI_FLOW }}                 # kosli-attestation-types-ci
  KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN }}
  KOSLI_TRAIL: ${{ github.sha }}

jobs:

  create-kosli-attestation-types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Kosli CLI
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: kosli-dev/setup-cli-action@v2
        with:
          version: ${{ vars.KOSLI_CLI_VERSION }}

      - name: Create test metrics attestation type
        if: ${{ github.ref == 'refs/heads/main' }}
        run:
          kosli create attestation-type test-metrics
            --schema=test-metrics.schema.json
            --jq ".test_count >= .variables.min.test_count"
            --jq ".total_time <= .variables.max.total_time"
            --jq ".failure_count == 0"
            --jq ".error_count == 0"
            --jq ".skip_count == 0"
